apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: safe-tests
spec:
  project: safe-project
  source:
    chart: nginx
    repoURL: registry-1.docker.io/bitnamicharts  # note: the oci:// syntax is not included.
    targetRevision: 15.9.0
  destination:
    name: "in-cluster"
    namespace: safe-tests